### ISSUE TITLE
Tearing issue

### ISSUE THREAD

**Issue by Edzolphire** [Venipa/discord-dark-anime#3]
Hello ! i absolutely love the theme and i have two questions about it : the first one is about the weird tearing in the chat box, it looks like this http://prntscr.com/mssutr, is it normal ? second is i found your theme with this site https://betterdocs.us/themes/discord-dark-koi/ and the theme looks very different and even has a background picture, is it the same theme or are they different ? thank you for your time !

**Comment by Venipa** [comment]
its an box-shadow issue will be replaced with a gradient.
the theme got updated quite a bit tho we didnt updated the screenshots. (will be changed in the next commits probably)
Thanks for the issue

**Comment by Venipa** [comment]
fixed in 821687394b2348fb7238c541a1f4651eef89fd4c if it still happens i may redesign the whole message wrapper with a different approach.
