### ISSUE TITLE
Discord Dark Koi - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by Kagero117** [Venipa/discord-dark-anime#5]
Hello there, i already sent a ticket telling you that i didn't work. Well, i didn't tell you well what i meant...what i meant, is that i can't download your theme, because when i click on the dl button, it leads me to 'Code>Release>Import>Theme' section, and even with the 'For normies' post, the link below leads me to nothing, it downloads me nothing, can i get any help kind sir ?

**Comment by Venipa** [comment]
the tutorial i wrote worked.
press the link instead of going through the folders.
