### ISSUE TITLE
Avatar infinite loading in messages / Discord Folder Update - Discord Dark Anime -[Issue Report]

### ISSUE THREAD

**Issue by Pandraemonium** [Venipa/discord-dark-anime#6]
Hi, i just installed your theme and i liking it so far but i got 2 issues with it.

1st one is an error with all avatars in messages on every servers

And the 2nd one is comming from the folder update that discord pushed, i assume the theme was released before that so i understand it's not working as intended but i took a screenshot to show you.

Folders and private message icon seems to be too big unfortunatly.

**Comment by Venipa** [comment]
avatar & folder sizing has been fixed in the latest release a63eb2e65dbaa078ae550d92381568b56902105a

**Comment by Draewyn** [comment]
![Github](https://user-images.githubusercontent.com/9287378/62452434-79d91200-b770-11e9-8c13-d7267ea07890.png)

Working like a charm now, thank you very much for the fix !
