### ISSUE TITLE
Few visual issues with Dark Koi theme since Light theme discord update.

### ISSUE THREAD

**Issue by Pandraemonium** [Venipa/discord-dark-anime#7]
Hello,

A few visual issues has appeared since the very last update of discord, here are what i've seen so far :

- Left Channel Panel is not anymore customizable with the "--dda-channel-background:url(yoururlhere);"
- Profile layout is half broken, when you click on your profile in the chat it appear with the Dark Koi layout, when you click to someone's profile directly from the server list, it appears the old discord way.
- Mentions are not using the Dark Koi Layout anymore, it's using the yellow background from discord.
- "New message" pop up is also broken and doesn't appear anymore.

The version used of the Theme is the latest one : Dark Koi v0.8.4-pre

It's all i've seen for the moment, thank you very much for your theme and sorry for the disturbance.

Have a nice day !

**Comment by Venipa** [comment]
I will update this theme asap :)

**Comment by Pandraemonium** [comment]
No problem take your time, i just wanted to share what's broken. 
I also founded something else. The user audio is broken too.

Thank you again !
![Audio](https://user-images.githubusercontent.com/9287378/64796757-7cedcc00-d580-11e9-947f-801613bf500d.png)

**Comment by lukeacat** [comment]
![image](https://user-images.githubusercontent.com/35845382/67300883-5e6fde80-f4f7-11e9-8d95-52c0c5a811c7.png)

Background not applying correctly

**Comment by Venipa** [comment]
@kuteshiki has been updated, may take a while until the cdn updates my css file

**Comment by Venipa** [comment]
User Popout has also been fixed

5cf3efbfeb9f0a9e9c7b08063afd33adcbff83dd
b6a0a42659dc2f03089ecbbc88f367d8bb9bfef0
